export const BREADCRUMB_PUSH = 'BREADCRUMB_PUSH'
export const BREADCRUMB_REPLACE = 'BREADCRUMB_REPLACE'
export const BREADCRUMB_GO = 'BREADCRUMB_GO'
export const BREADCRUMB_RENAME_LAST_ELEMENT = 'BREADCRUMB_RENAME_LAST_ELEMENT'
export const BREADCRUMB_CLEAR = 'BREADCRUMB_CLEAR'
export const SET_ROOT_VIEW = 'SET_ROOT_VIEW'
export const CLEAR_VIEW = 'CLEAR_VIEW'

export const SUB_BREADCRUMB_PUSH = 'SUB_BREADCRUMB_PUSH'
export const SUB_BREADCRUMB_CLEAR = 'SUB_BREADCRUMB_CLEAR'
export const SUB_BREADCRUMB_REPLACE = 'SUB_BREADCRUMB_REPLACE'
export const SUB_BREADCRUMB_GO = 'SUB_BREADCRUMB_GO'
export const SUB_BREADCRUMB_RENAME_LAST_ELEMENT = 'SUB_BREADCRUMB_RENAME_LAST_ELEMENT'
export const CLEAR_ALL_SUB_BREADCRUMBS = 'CLEAR_ALL_SUB_BREADCRUMBS'

export const USER_DATA = 'USER_DATA'
export const PROFILE_DATA = 'PROFILE_DATA'
export const APP_SETTINGS = 'APP_SETTINGS'
export const SET_MODULES = 'SET_MODULES'
export const SET_CURRENT_MODULE_AND_SECTION = 'SET_CURRENT_MODULE_AND_SECTION'
export const ENUMS = 'ENUMS'
export const RESOURCES_AND_ACTIONS = 'RESOURCES_AND_ACTIONS'
// Системные параметры(максимальный размер файла и тд)
export const SYSTEM_PARAMETERS = 'SYSTEM_PARAMETERS'

// Справочники
export const SET_TERRITORIES = 'TERRITORIES'
export const SET_TERRITORIES_TREE = 'TERRITORIES_TREE'
export const URBAN_PLANNING_OBJECTS = 'URBAN_PLANNING_OBJECTS'

export const EVENT_PROFILE_DATA = 'EVENT_PROFILE_DATA'

export const MAP_TOGGLE_SIDEBAR = 'MAP_TOGGLE_SIDEBAR'
export const MAP_OPEN_SIDEBAR = 'MAP_OPEN_SIDEBAR'
export const MAP_CLOSE_SIDEBAR = 'MAP_CLOSE_SIDEBAR'
export const MAP_INITIALIZE = 'MAP_INITIALIZE'
export const MAP_SET_SEARCH_RESULTS = 'MAP_SET_SEARCH_RESULTS'
export const MAP_SET_LAYERS_HASH = 'MAP_SET_LAYERS_HASH'
export const MAP_CLEAR_SEARCH_RESULTS = 'MAP_CLEAR_SEARCH_RESULTS'

export const SET_BEFORE_LEAVE_FUNC = 'SET_BEFORE_LEAVE_FUNC'
