import 'vue-select/dist/vue-select.css'
import 'roboto-fontface/css/roboto/roboto-fontface.css'
import '^/assets/gprime-font/iconfont.css'

import 'bootstrap/dist/css/bootstrap.css'

import '^/theme/css/app.css'
import '^/theme/css/select2.css'
import '^/theme/css/nouislider.css'
import '^/theme/css/fullcalendar.css'
import '^/theme/css/tree.css'
import '^/theme/css/panel.css'
import '^/theme/css/datatable.css'
import '^/theme/css/defaultcolors.css'
import '^/theme/css/checker.css'

import 'pace'
import 'bootstrap'
import 'jquery.nicescroll'
import 'jquery-validation'
import 'blockui'
import 'select2'
import 'bootstrap-fileinput'
import 'bootstrap-fileinput/js/locales/ru.js'
