
// Наименования событий для карты.
export default {
  ADD_REGISTRY_LAYER: 'ADD_REGISTRY_LAYER',
  CLEAR_HIGHLIGHT_OBJECTS: 'CLEAR_HIGHLIGHT_OBJECTS',
  SHOW_REGISTRY_OBJECT: 'SHOW_REGISTRY_OBJECT',
  ADD_REGISTRY_LAYER_AND_SHOW_OBJECT: 'ADD_REGISTRY_LAYER_AND_SHOW_OBJECT',
  GET_COORDINATES: 'GET_COORDINATES',
  COORDINATES_RESULT: 'COORDINATES_RESULT',
  CHANGE_GEOMETRY: 'CHANGE_GEOMETRY',
  ZOOM_TO_GEOMETRIES: 'ZOOM_TO_GEOMETRIES',
  SHOW_REQUEST_OBJECT: 'SHOW_REQUEST_OBJECT'
}
